### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by scop** [home-assistant/hassio-cli#101]
Would be great to have a new release out with the bash completion included, to make it possible to cleanly do an update to the ssh addon and include the completion in it :)

**Comment by pvizeli** [comment]
@scop that is actual not maintained :(

Do you want maintain this project?

**Comment by scop** [comment]
Ah, disappointing to hear that. And unfortunately I don't think I have time to help out too much here either in the long term, sorry.

**Comment by frenck** [comment]
We are looking into getting some small updates en fixes right now.
