### ISSUE TITLE
Rewrite CLI to use Cobra

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio-cli#109]
# Problem/Motivation

Cobra is both a library for creating powerful modern CLI applications as well as a program to generate applications and command files.

The CLI needs to be rewritten to use Cobra instead of the current solution.

While doing this, it would be nice to review/reconsider the current directory setup. For example, a code structure where each command has its own file.

E.g.: `hassio homeassistant restart` -> `commands/homeassitant/restart.go`

This would give is more flexibility towards the future and a more easily understandable code base.

# Ref

https://github.com/spf13/cobra

**Comment by bbriggs** [comment]
I'll take this one.

**Comment by balloob** [comment]
Cool! If you want intermediary feedback, open a PR early.

**Comment by bbriggs** [comment]
Sure. I'll send an incremental PR in a day or so.

**Comment by frenck** [comment]
(wrong button)

**Comment by chriscla** [comment]
@bbriggs  are you still working on this? I'm an extreme go n00b but would be interested in trying this.

**Comment by balloob** [comment]
@chriscla you can go for it.

**Comment by mjrider** [comment]
@chriscla because multiple issues (#109, #111, and other developement) would require extensive rewrites, @frenck and I decided today to create a branch next, which based on current dev + #117 
Hoping that collaborators can team up with in writing version 2. I hope this doesn't set you back to far in your development

**Comment by chriscla** [comment]
HI @mjrider  -- I probably bit off a bit more than I can chew and was starting from the beginning.  I would love to contribute with others to the work on doing this.

**Comment by bbriggs** [comment]
Hey guys, yeah I'm still working on it. Much apologies, I had an unexpected three weeks of travle. 

@chriscla, I'd be happy to pair with you on this if you want. I'm going to rebase some of those other PRs back in and resume work.

**Comment by MattNolf** [comment]
I'd like to get involved with this if it's still open?

**Comment by mjrider** [comment]
yeah ofcourse
on my short todo list:

- [ ] Fix that HASSIO_TOKEN as env key is also useable
- [ ] REadded rawjson as root option, and use it in the display function for json data

**Comment by mjrider** [comment]
if ppl still want to help, i think  all the changes which needed to be done are now finished, and it needs some testers.
The binaries are downloadable here: https://github.com/home-assistant/hassio-cli/releases/tag/2.0.0-rc2

**Comment by mjrider** [comment]
Fixed in #127 
merged in dev in commit fca215d405f3ab342b065d3c23ead9a652c7a466
