### ISSUE TITLE
Add output handling using Logrus

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio-cli#110]
The CLI now mostly output to the standard output using simple print calls.

Nevertheless, the use of a proper logging library would, of course, be the preferred solution.

One of the most used libraries seems to be Logrus:

https://github.com/sirupsen/logrus

This seems to be a proper solution, nevertheless, other suggestions are welcome.

**Comment by rafa-acioly** [comment]
can i take this one @frenck ?

**Comment by rafa-acioly** [comment]
i've sended you a PR https://github.com/home-assistant/hassio-cli/pull/112

**Comment by mjrider** [comment]
I added a PR as well, i was already working on this before the issue was opened.
major differences is that i use the WithFields option of logrus, instead of fprintf and i removed the debug flag from the codebase and use the loglevel for selecting which messages should be shown

**Comment by zpeters** [comment]
help needed with this, or are we good?

**Comment by balloob** [comment]
We're good.
