### ISSUE TITLE
Rewrite Hassio API handling/library

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio-cli#111]
The current handling of the communication with the Hassio API is not a very robust one.
We have "fixed" a couple of things, to prevent stuff from breaking (even worse, we just hide errors on some places).

A proper library / API handler would be really great. We have looked a bit at Resty:

https://github.com/go-resty/resty

This is mainly because it is well documented, easy to use and understand.

Other solutions are welcome as well.

PR's for this issue should target the next branch

**Comment by rubiagatra** [comment]
I am interested in this, actually, I really don't know about a good library / API handler, I think resty really good for the job. Is there something wrong with the standard library? @frenck ?

**Comment by gillchristian** [comment]
@rubiagatra this one might simplify things a bit https://github.com/asmcos/requests

**Comment by mjrider** [comment]
Fixed in #127 
merged in dev in commit fca215d405f3ab342b065d3c23ead9a652c7a466
