### ISSUE TITLE
Documentation in readme.md not up to date 

### ISSUE THREAD

**Issue by mjrider** [home-assistant/hassio-cli#138]
The readme.md was not updated with the v2 rewrite.
This needs to be fixed,

**Comment by scop** [comment]
I'm wondering in particular whether the tool is supposed to install as the name `hassio` like before, or `hassio-cli`. README.md refers to `hassio`, but for example the bash completion emitted with the `completion` option results in a completion file that only installs the completion for `hassio-cli`, no matter what the name of the command that is used to output the completion is.

**Comment by mjrider** [comment]
@scop you have a good point, and you should open an issue for that
