### ISSUE TITLE
hassio ha update with version option fails

### ISSUE THREAD

**Issue by cogneato** [home-assistant/hassio-cli#142]
A version can be specified for a downgrade using `hassio ha up version=0.85.0b0` successfully.

When updating to a new release (.0b0 to .0b1 for example) the command returns "ok" and the update does not occur, with supervisor logs returning `WARNING (MainThread) [hassio.homeassistant] Version 0.85.0b0 is already installed`

**Comment by cogneato** [comment]
Now since updating to release of .85.0 the command does not work to downgrade to .85.0b0 and returns the same warning `Version 0.85.0 is already installed`

**Comment by mjrider** [comment]
Hello @cogneato 
i just tried the following scenario
- update to 0.85.0b0 from 0.84.x
- update to 0.85.0
- downgrade to 0.85.0b0

and it works like expected.

The logic how to handle the update is in the supervisor (iirc) the cli just send the requested version to the supervisor without any logic
requesting to update to version foobar  also works, except the supervisor has an opinion about the existence of that version

**Comment by cogneato** [comment]
Hey @mjrider 
Are you using the same command as I used above? I've tried both the ssh server and ssh & web terminal addons and get the same 'ok' result immediately no matter what version I enter now.

**Comment by cogneato** [comment]
My fault. I thought I had used `--version=` but switched at some point to `version=` and that's been the problem the whole time. Sorry.
