### ISSUE TITLE
how to use --api-token?

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/hassio-cli#148]
I'm trying to automate command line access to the hassio CLI and I can't figure out how to use the --api-token argument.  I get an error without it saying that I need to specify a token, but if I create a long-life-access-token in the UI and use it, I get a "403 Forbidden" message in hassio-cli and this in the system log:

`19-03-22 19:05:09 ERROR (MainThread) [hassio.api.security] Invalid token for access /homeassistant/info`

I can't find that message anywhere in the Hass code, and I've looked through all the auth sections for what could be wrong.  It looks like the hassio component may require a username/password?  But then I don't know how to specify that to hassio-cli.

Any pointers?

**Comment by rccoleman** [comment]
Solved my own problem in several ways, documented here: https://community.home-assistant.io/t/using-long-lived-access-tokens-to-execute-hassio-commands-over-ssh/106878/2

**Comment by frenck** [comment]
@rccoleman That seems incorrect.
 The token needed is an Hass.io API token, not a Home Assistant token.

You can use the remote API developers add-on to get an endpoint & token: <https://github.com/home-assistant/hassio-addons-development>

**Comment by rccoleman** [comment]
Thanks for the link.  Which part do you think is incorrect?  I'm using the last one on a regular basis now.

**Comment by frenck** [comment]
@rccoleman 

![image](https://user-images.githubusercontent.com/195327/55273096-9d71e480-52c6-11e9-9f51-3c2480f60773.png)

While you can use an HA API token for HA related calls, this will not work on ALL the other calls.
