### ISSUE TITLE
Command Not Found In git_pull Addon

### ISSUE THREAD

**Issue by strangiato** [home-assistant/hassio-cli#160]
**Describe the bug**
The [git_pull addon](https://github.com/home-assistant/hassio-addons/tree/master/git_pull) is experiencing an issue resulting in the addon to throw the following error:

`
/usr/bin/hassio: line 1: Not: command not found [Error] Configuration updated but it does not pass the config check. Do not restart until this is fixed!
`

It appears the issue is possibly with a build of the 2.0.1 CLI the Docker container uses for ARM.

More users have reported the issue [here](https://github.com/home-assistant/hassio-addons/issues/556).

**Debug info**
1. SSH Addon type:
- [x] Community
- [ ] Core
- [ ] Custom

2. Output of `hassio --version`
hassio --version is not a known command. I ran hassio info and got this:

arch: armv7
channel: stable
hassos: "2.11"
homeassistant: 0.91.4
hostname: hassio
logging: info
machine: raspberrypi3
supervisor: "162"
supported_arch:
- armv7
- armhf

3. Version of Hassio / Home Assistant
0.91.4

4. Output from executing the command with debug info.
e.g. `hassio hardware info` should be run as `hassio -d hardware info`
audio:
  "0":
    devices:
    - chan_id: "0"
      chan_type: digital audio playback
    - chan_id: "1"
      chan_type: digital audio playback
    name: bcm2835_alsa - bcm2835 ALSA
    type: ALSA
disk: []
gpio:
- gpiochip0
- gpiochip100
- gpiochip128
input: []
serial:
- /dev/ttyAMA0

**Expected behavior**
When the addon executes `hassio homeassistant check` it should successfully run the check command instead of returning an error on hassio.

**Additional context**
e.g. If you are running `hassio homeassistant check` and the config is known to be broken or good.

**Comment by frenck** [comment]
This has already been fixed in the add-on.
