### ISSUE TITLE
Spinner eats lines when using SSH

### ISSUE THREAD

**Issue by MarcHagen** [home-assistant/hassio-cli#179]
**Describe the bug**
On running `hassio ha check` the spinner causes the Task line to eat (backspace) all characters on the line that it is on, then it moves to the line above and continues until the task line with Spinner are sitting in the top left corner. There is happily spins until the task is done.

**Debug info**
1. SSH Addon type:
- [ ] Community
- [x] Core (Version: 6.3)
- [ ] Custom

2. Output of `hassio --version`
```
core-ssh:~# hassio os info
board: ova
version: "2.12"
version_cli: "14"
version_cli_latest: "14"
version_latest: "2.12"
```

3. Version of Hassio / Home Assistant
HassOS 2.12 - Hass.io supervisor 184
Home Assistant 0.97.2

4. Output from executing the command with debug info.
e.g. `hassio hardware info` should be run as `hassio -d hardware info`
```
Proxmox VM
core-ssh:~# hassio hardware info
audio: {}
disk: []
gpio: []
input:
- QEMU QEMU USB Tablet
- ImExPS/2 Generic Explorer Mouse
- Power Button
- AT Translated Set 2 keyboard
serial:
- /dev/ttyS1
- /dev/ttyS2
- /dev/ttyS3
- /dev/ttyS0
```

**Expected behavior**
That the spinner only spins on its current line and not eat everything above it.

**Additional context**
Output of the command:
```
Processing... Done.
                ⡿ Processing...
Command completed successfully.
core-ssh:~#     ⣾ Processing...
                ⣯ Processing...
                ⡿ Processing...
                ⣻ Processing...
                ⣾ Processing...
                ⣯ Processing...
                ⡿ Processing...
                ⣻ Processing...
                ⣾ Processing...
                ⣯ Processing...
                ⡿ Processing...
                ⣻ Processing...
  Processing...
```

**Comment by pvizeli** [comment]
Yeah, I have the same issue but only with putty

**Comment by frenck** [comment]
So weird, I've tested this thing with so many clients (even webbased ones), however, not Putty (since well, I don't have windows). Will try to see what is causes, just weird.

**Comment by redlegoman** [comment]
I just left a comment on the PR, probably the wrong place, so here's the gif of what happens in Putty. I tried TERM=xterm and TERM=linux, both with the same results
![gif1](https://user-images.githubusercontent.com/1895294/64270940-51d9fb80-cf34-11e9-8d35-957893bee7ff.gif)
