### ISSUE TITLE
Feature Request: hassio [ha | supervisor] logs --follow

### ISSUE THREAD

**Issue by mgriffin13** [home-assistant/hassio-cli#186]
It would be really nice if the hassio-cli tool supported following logs (basically a tail -f equivalent), so that you can have real-time updates when you're trying to debug things. This is a common feature in most log analysis tools.

I would expect something like this to work

```
hassio ha logs --follow
hassio supervisor logs -f
```

**Comment by frenck** [comment]
The Hass.io CLI cannot add this, since there is no hook for this available on the end of the Hass.io API.

Nevertheless, thank you for your suggestion.
