### ISSUE TITLE
Add support for enabling zwave

### ISSUE THREAD

**Issue by ryanm101** [home-assistant/hassio-cli#21]

**Comment by pvizeli** [comment]
What you mean with this?

**Comment by ryanm101** [comment]
I read somewhere there are some instances were the device needs to be set via curl command
this is just to add it as a direct call

**Comment by ryanm101** [comment]
https://community.home-assistant.io/t/help-setup-aeotec-z-wave-usb-stick/37001/3

**Comment by pvizeli** [comment]
That is gone with 0.79
