### ISSUE TITLE
Check command should return non zero exit code on failure

### ISSUE THREAD

**Issue by SteveEdson** [home-assistant/hassio-cli#35]
`hassio homeassistant check` should return a failure exit code if the config is invalid. This will make it easy to run commands like `git pull && hassio homeassistant check && hassio homeassistant restart`.

Currently, the restart command would be called even if the config is invalid.

Alternatively, the restart command could have a flag that checks the config is valid first.

**Comment by ryanm101** [comment]
Yes, for the sake of simplicity I force you to check the "result". 

Next version will tie result to return codes.

**Comment by ryanm101** [comment]
@SteveEdson Can you please verify it doesnt do this I just checked code and error code 10 should come back if result is not OK.

**Comment by SteveEdson** [comment]
@ryanm101 has this changed recently? It wasn't doing this when I opened the ticket, but it seems to have updated itself and now uses the correct exit codes.

Thanks either way!

**Comment by ryanm101** [comment]
not that part. Unless you were using the previous bash script but i thought it did the right thing too
