### ISSUE TITLE
Add Support for partial snapshots

### ISSUE THREAD

**Issue by ryanm101** [home-assistant/hassio-cli#61]
We currently support Full Snapshots, but due to the number of options for partials they weren't implemented in the 1st pass.

**Comment by frenck** [comment]
This should probably be done after #109.

**Comment by mjrider** [comment]
i think that i already implemented this in in #109 , or i'm misunderstanding the issue

**Comment by mjrider** [comment]
Fixed in #127 
merged in dev in commit fca215d405f3ab342b065d3c23ead9a652c7a466
