### ISSUE TITLE
Add Support for Services

### ISSUE THREAD

**Issue by ryanm101** [home-assistant/hassio-cli#62]
https://github.com/home-assistant/hassio/blob/dev/API.md
GET /services/discovery
GET /services/discovery/{UUID}
POST /services/discovery
DEL /services/discovery/{UUID}

GET /services
GET /services/xy
GET /services/mqtt
POST /services/mqtt
DEL /services/mqtt

**Comment by frenck** [comment]
Maybe later, there is no direct need for it right now.
