### ISSUE TITLE
"hassio snapshots info -name xxxxxx" requires snapshot slug identifier, not snapshot name

### ISSUE THREAD

**Issue by MojaveTom** [home-assistant/hassio-cli#66]
> hassio help snapshots
> NAME:
>    hassio snapshots - list, info, reload, new, restore, remove
> 
> USAGE:
>    hassio snapshots [command options] [arguments...]
> 
> OPTIONS:
>    --rawjson, -j                                      Returns the output in JSON format
>    --options key=val,key2=val2, -o key=val,key2=val2  holds data for POST in format key=val,key2=val2
>    --filter prop1,prop2, -f prop1,prop2               properties to extract from returned data prop1,prop2
>    --name nameofsnapshot                              used with 'info|remove|restore|full' actions to return info on a specific snapshot nameofsnapshot
> 

   
As documented in the hassio help for snapshots, the --name argument for the info command takes the name of a snapshot.
The REST API for hassio says that the "slug" of the snapshot is required for info.

I suggest that either the help for snapshots show that the slug identifier is desired, OR the snapshots command should accept the name of the snapshot and translate it to the slug identifier for the REST GET command.

**Comment by ryanm101** [comment]
https://github.com/home-assistant/hassio-cli/pull/69
