### ISSUE TITLE
This repository need follow HomeAssistant style guide a bit

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/hassio-cli#68]
I'm fine with autoformating but we now the only repo with 8 space. We need revert this back to 4 space and pin that.

**Comment by pvizeli** [comment]
Minimum of style is:
- 4 space, no tabs
- 80 character lines

**Comment by pvizeli** [comment]
Fix with https://github.com/home-assistant/hassio-cli/commit/4ee40a1ba12f83b800791d10ac3d881c1be7754f

**Comment by ryanm101** [comment]
I'll need to read more about this but looking at it gofmt and "go" in general dont seem to "allow" any other style. https://github.com/golang/go/issues/16256

On one hand I can see the point in being consistent across the project (and that will likely win) however the point made in the other thread is valid in that those styles are pythonic not GO. 

Now if we were relying on the developers to maintain formatting then yes i can see a reason for having a "style guide" but if we use a tool to actually format and enforce the format then that argument in my opinion becomes weaker. 

As I said in the previous post consistency is key, however when I say that in my opinion that is most important within the same repository once outside of a repo the argument while valid is less important. 

Personally I'm a fan of 4 spaces / no tabs, but equally I dont really care enough to make a fuss if someone used 2 or 6 or 8 spaces as long as ALL the code was the same.

**Comment by ryanm101** [comment]
https://golang.org/doc/effective_go.html#formatting

**Comment by moorereason** [comment]
I know very little about the HA community.  It's your project.  You guys do what you want.  However, ...

Any time I see a Go package that doesn't use gofmt, I immediately assume the project is of poor quality.  I feel the same way about a Python package that doesn't follow PEP8. It's more about being a good member of the Go or Python communities than it is about whitespace.

PS: It's Go, not GO.

**Comment by ryanm101** [comment]
Tbh that's a bit like judging a book by its cover. PEP8 and gofmt are simply suggestions not law, if they were it would be built into the syntax like python does with indenting instead of brackets. I would almost agree with you if there was no consistent styling at all.

**Comment by pvizeli** [comment]
This issue is while golang is not a very popular language and there are not many tools around for handling code. Like c++ there are a lot different style guides and tools they can format the code for any company.

It's funny that some kids by google want define how code should look like. That is a old war from indent to space ect.

**Comment by ryanm101** [comment]
@pvizeli After doing a bit more reading I agree we should revert the code back to the project standard. 
I hadn't initially realised but gofmt uses tab, while I agree with the logic of 'letting the machine handle it' and I am a big big fan of the idea of just using a tool to do it and enforce it. The style has not been a problem todate and tabs are pure evil if your editor has anything other than 4 spaces per tab.
