### ISSUE TITLE
Add "Spinner" to show that cli hasnt hung when awaiting a return from API

### ISSUE THREAD

**Issue by ryanm101** [home-assistant/hassio-cli#70]
Some commands can take quite a while to complete, but there is currently no feedback to the user.

The suggestion now is to add a spinner when a command is pending answer from the server.

Example library that could be used:

https://github.com/briandowns/spinner

Any other suggestions or improvements in this department are, of course, welcome as well.

**Comment by quamilek** [comment]
I will take this issue.

**Comment by frenck** [comment]
Closing this issue, since, well, commands are pretty fast now 👍
