### ISSUE TITLE
Add new line at end of return message from CLI

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/hassio-cli#84]
Running CLI commands with a message being returned makes the terminal flow break a bit. It's an enhancement I know, but would be useful to have it. 

Actual:
```bash
core-ssh:~# hassio ho restart
No valid action detectedcore-ssh:~# hassio ho reboot
```

Expected:
```bash
core-ssh:~# hassio ho restart
No valid action detected
core-ssh:~# hassio ho reboot
```

**Comment by ryanm101** [comment]
this was merged https://github.com/home-assistant/hassio-cli/pull/85
