### ISSUE TITLE
Display build output when installing local addons

### ISSUE THREAD

**Issue by ndarilek** [home-assistant/hassio-cli#89]
Hey, new to hassio so I'm not sure if I'm doing things correctly. I'm trying to build my first addon for the Mycroft voice assistant. I have a Dockerfile that I've confirmed builds on another RPi, and now I'm trying to build it as a hassio addon. The files are in /addons/mycroft, and I run:

```bash
$ hassio ad install -name local_mycroft
```

At this point my session hangs and I get no output.

Is this how I'd go about building a local addon? If so, how do I inspect the build logs in case of failure? I thought it'd be enough to try building the image on the identical pi running plain Raspbian, but it seems to be failing in hassio and I don't know why without logs.

Thanks.

**Comment by frenck** [comment]
Try to build you add-on locally first, using plain Docker.
Did you try that already?

**Comment by ndarilek** [comment]
Yeah, it works fine.

I think what may be happening here, or at least what's causing the 
failure, is that the Pi is running too many addons to perform the build. 
When I successfully build, it's on a plain Raspbian image that isn't 
running anything. But it'd be nice if the installation actually logged 
something, because as of now I'm just guessing as to what may be going 
wrong.

**Comment by frenck** [comment]
I do agree, but that is not a CLI problem.
The CLI is not fed with logs.
Going to move the issue into the `hassio` repository in that case.

**Comment by frenck** [comment]
Ok, so the move bot is not installed here 👎 
@ryanm101 ?

**Comment by ryanm101** [comment]
@frenck it is showing as installed, but "configure" is greyed out. @pvizeli?

**Comment by frenck** [comment]
@ryanm101 #91

**Comment by ryanm101** [comment]
@frenck THanks
