### ISSUE TITLE
ERROR: panic: interface conversion: interface is nil, not string

### ISSUE THREAD

**Issue by msanchezt** [home-assistant/hassio-cli#98]
**Describe the bug**
After running "hassio ha restart" I got the error:

```
core-ssh:/config# hassio -d ha restart
DEBUG [CmdHomeassistant]: action->'restart', endpoint='restart', serverOverride->'', GET->'false', options->'', rawjson->'false', filter->''
DEBUG [ExecCommand]: basepath->'homeassistant', endpoint->'restart', serverOverride->'', get->'false', Options->'', Filter->'', RawJSON->'false'
DEBUG [GenerateURI]: basepath->'homeassistant', endpoint->'restart', serverOverride->''
DEBUG [RestCall]: data->'http://hassio/homeassistant/restart', GET->'false', payload->''
DEBUG [RestCall]: ResponseBody->'{"result": "error", "message": null}'
ERROR
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x2f8720, 0x44200a0800)
	/home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x390
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0x4420132200, 0x24, 0x200, 0x0)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x404
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x345e94, 0xd, 0x7ff015be56, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x31c
github.com/home-assistant/hassio-cli/command.CmdHomeassistant(0x44200ea420)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/homeassistant.go:48 +0x540
github.com/urfave/cli.HandleAction(0x2dc640, 0x372ff0, 0x44200ea420, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0x118
github.com/urfave/cli.Command.Run(0x345e94, 0xd, 0x0, 0x0, 0x49a280, 0x1, 0x1, 0x350d84, 0x2f, 0x0, ...)
	/home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x7b0
github.com/urfave/cli.(*App).Run(0x4420104000, 0x442000a100, 0x4, 0x4, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x950
main.main()
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +0x150
```

Tried restarting the RPi3, disconnecting some of the components.
Also tried restoring previous version of the configuration files (had a rsync backup), same result.
Restoring snapshot doesn't solve the issue neither.

**Debug info**
1. SSH Addon type:
- [ ] Community
- [X] Core
- [ ] Custom

2. Output of `hassio --version`

> hassio version 1.3.1

3. Version of hassio / homeassistant

>         "version": "0.75.3",

4. Output from executing the command with debug info.

> core-ssh:/config# hassio -d hardware info
> DEBUG [CmdHardware]: action->'info', endpoint='info', serverOverride->'', GET->'true', options->'', rawjson->'false', filter->''
> DEBUG [ExecCommand]: basepath->'hardware', endpoint->'info', serverOverride->'', get->'true', Options->'', Filter->'', RawJSON->'false'
> DEBUG [GenerateURI]: basepath->'hardware', endpoint->'info', serverOverride->''
> DEBUG [RestCall]: data->'http://hassio/hardware/info', GET->'true', payload->''
> DEBUG [RestCall]: ResponseBody->'{"result": "ok", "data": {"serial": ["/dev/ttyAMA0"], "input": [], "disk": [], "gpio": ["gpiochip0", "gpiochip128"], "audio": {"0": {"name": "bcm2835_alsa - bcm2835 ALSA", "type": "ALSA", "devices": {"0": "digital audio playback", "1": "digital audio playback"}}}}}'
> {
>     "result": "ok",
>     "data": {
>         "serial": [
>             "/dev/ttyAMA0"
>         ],
>         "input": [],
>         "disk": [],
>         "gpio": [
>             "gpiochip0",
>             "gpiochip128"
>         ],
>         "audio": {
>             "0": {
>                 "name": "bcm2835_alsa - bcm2835 ALSA",
>                 "type": "ALSA",
>                 "devices": {
>                     "0": "digital audio playback",
>                     "1": "digital audio playback"
>                 }
>             }
>         }
>     }
> }

**Expected behavior**
After restarting hassio, should start properly.

**Additional context**
`hassio homeassistant check` returns OK.

Can't figure out where the error/issue is, as error is quite vague.

**Comment by frenck** [comment]
This error has been fixed in version 1.4.0.
